esp8266:
  board: d1_mini

esphome:
  name: delta-tango
  name_add_mac_suffix: true

# I2C for SDP810 pressure sensor (when added)
i2c:
  sda: GPIO4  # D2
  scl: GPIO5  # D1

# OneWire bus for DS18B20 temperature sensors
dallas:
  - pin: GPIO2  # D4 - moved from GPIO12 for better layout
    update_interval: 30s

sensor:
  # SDP810 Pressure Sensor (uncomment when hardware is added)
  # - platform: sdp3x
  #   name: "HVAC Static Pressure"
  #   accuracy_decimals: 1
  #   update_interval: 5s

  # DS18B20 Temperature Sensors
  - platform: dallas
    name: HVAC Return Air Temperature
    id: hvac_return_air_temperature
    index: 0
    accuracy_decimals: 2
    
  - platform: dallas
    name: HVAC Supply Air Temperature
    id: hvac_supply_air_temperature
    index: 1
    accuracy_decimals: 2
    
  # Calculated Delta-T sensors
  - platform: template
    name: HVAC Delta T (째C)
    lambda: 'return id(hvac_return_air_temperature).state - id(hvac_supply_air_temperature).state;'
    accuracy_decimals: 2
    update_interval: 1s
    unit_of_measurement: "째C"
    
  - platform: template
    name: HVAC Delta T (째F)
    lambda: |-
      const float hvac_return_air_temperature_f = (id(hvac_return_air_temperature).state * 9/5) + 32;
      const float hvac_supply_air_temperature_f = (id(hvac_supply_air_temperature).state * 9/5) + 32;
      return hvac_return_air_temperature_f - hvac_supply_air_temperature_f;
    update_interval: 1s
    accuracy_decimals: 2
    unit_of_measurement: "째F"

dashboard_import:
  package_import_url: github://brobstoncreations/delta-tango/delta-tango.yaml

captive_portal:

wifi:
  ap: {}
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   manual_ip:
#     static_ip: !secret static_ip
#     gateway: !secret gateway
#     subnet: !secret subnet

# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

web_server:

api:

mdns:
    
ota:

logger:
  level: INFO
